[package]
org = "motiondevs"
name = "gateway"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
artifactId = "sqlite-jdbc"
version = "3.42.0.0"
groupId = "org.xerial"

[tool.bal]
enableExperimentalFeatures = ["isolatedInferenceForRecord"]